In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# !nvidia-smi
print(torch.__version__)

2.1.0.dev20230613+cu117


# Tensor basics

### Creating tensors
PyTorch tensor are create using torch.Tensor()

In [3]:
# scalar
scalar = torch.tensor(7)
scalar 



7

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector magitude and direction
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [12]:
# first dimension
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6], [3,4,2]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [3, 4, 2]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 4, 2]])

In [20]:
TENSOR[0][0]

tensor([1, 2, 3])